# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Academimal"
license = "MIT"
licenselink = "https://github.com/yangl1996/academimal/blob/master/LICENSE"
description = "An uncluttered Hugo theme for academic researchers."
homepage = ""
tags = []
features = []
min_version = "0.41"

[author]
  name = "Lei Yang"
  homepage = "http://leiy.me"

# If porting an existing theme
[original]
  name = "Minimal"
  homepage = "https://pages-themes.github.io/minimal/"
  repo = "https://github.com/pages-themes/minimal"
