title = "Ricardo Dahis"
baseURL = "https://rdahis.github.io"
theme = "academimal"
languageCode = "en-us"

[author]
name = "Ricardo Dahis"
homepage = "https://www.ricardodahis.com"

[params]

shortbio = "Assistant Professor, PUC-Rio"
logo = "images/profile.jpg"

email = "rdahis@econ.puc-rio.br"
favicon = "/favicon.ico"
