title = "Ricardo Dahis"
baseURL = "https://rdahis.github.io"
theme = "academimal"
languageCode = "en-us"

[author]
name = "Ricardo Dahis"
homepage = "https://www.ricardodahis.com"

[params]

shortbio = "Assistant Professor, Monash University"
logo = "images/profile.jpg"

email = "ricardo.dahis@monash.edu"
favicon = "/favicon.ico"
